"""Utility modules for MCP Postgres server.

This package provides common utilities including input validation,
output formatting, custom exceptions, and helper functions.
"""

from .exceptions import (
    ColumnNotFoundError,
    ConfigurationError,
    ConnectionError,
    ConnectionPoolError,
    ConnectionTimeoutError,
    DatabaseError,
    DataIntegrityError,
    MCPPostgresError,
    ParameterValidationError,
    PermissionError,
    QueryError,
    QueryExecutionError,
    QuerySyntaxError,
    QueryTimeoutError,
    SecurityError,
    SQLInjectionError,
    TableNotFoundError,
    ToolError,
    ToolNotFoundError,
    ToolParameterError,
    TransactionError,
    ValidationError,
    handle_postgres_error,
)
from .formatters import (
    format_analysis_result,
    format_bytes,
    format_duration,
    format_error_response,
    format_performance_stats,
    format_query_result,
    format_success_response,
    format_table_info,
    format_table_list,
    serialize_dict,
    serialize_value,
    truncate_text,
)
from .helpers import (
    build_connection_string,
    calculate_similarity,
    chunk_list,
    create_pagination_info,
    deep_merge_dicts,
    extract_sql_operation,
    extract_table_names,
    flatten_dict,
    format_sql_query,
    generate_query_hash,
    get_current_timestamp,
    is_read_only_query,
    mask_sensitive_data,
    parse_connection_string,
    safe_cast,
    sanitize_identifier,
    validate_json_string,
)
from .validators import (
    sanitize_string_input,
    validate_column_name,
    validate_connection_params,
    validate_data_type,
    validate_limit_offset,
    validate_query_parameters,
    validate_sql_query_pattern,
    validate_table_name,
)


__all__ = [
    # Exceptions
    "MCPPostgresError",
    "ConnectionError",
    "ConnectionPoolError",
    "ConnectionTimeoutError",
    "QueryError",
    "QuerySyntaxError",
    "QueryExecutionError",
    "QueryTimeoutError",
    "ValidationError",
    "ParameterValidationError",
    "SecurityError",
    "PermissionError",
    "SQLInjectionError",
    "ConfigurationError",
    "DatabaseError",
    "TableNotFoundError",
    "ColumnNotFoundError",
    "TransactionError",
    "DataIntegrityError",
    "ToolError",
    "ToolNotFoundError",
    "ToolParameterError",
    "handle_postgres_error",

    # Validators
    "validate_table_name",
    "validate_column_name",
    "validate_query_parameters",
    "validate_limit_offset",
    "validate_sql_query_pattern",
    "validate_data_type",
    "validate_connection_params",
    "sanitize_string_input",

    # Formatters
    "format_query_result",
    "format_table_info",
    "format_analysis_result",
    "format_error_response",
    "format_success_response",
    "format_table_list",
    "format_performance_stats",
    "serialize_value",
    "serialize_dict",
    "format_bytes",
    "format_duration",
    "truncate_text",

    # Helpers
    "parse_connection_string",
    "build_connection_string",
    "extract_table_names",
    "generate_query_hash",
    "chunk_list",
    "flatten_dict",
    "deep_merge_dicts",
    "safe_cast",
    "get_current_timestamp",
    "calculate_similarity",
    "extract_sql_operation",
    "is_read_only_query",
    "sanitize_identifier",
    "format_sql_query",
    "validate_json_string",
    "create_pagination_info",
    "mask_sensitive_data",
]
